const productCategories = {
  Sticker: 0,
  Patttern: 1,
};

const products = [
  {
    productID: 0,
    productName: "Dandelion Fluff Pattern",
    productDescription: `Introducing the 8 Seamless Dandelion Pattern Pack available on Etsy! This stunning collection offers a range of captivating dandelion-themed patterns, perfect for adding a touch of natural beauty to your creative projects.`,
    productPrice: 2.99,
    productCategory: productCategories.Sticker,
    discountRate: 0,
    productThumbnailPath: "/pattern-pictures/dandelion/1.webp",
    productImages: [
      "/pattern-pictures/dandelion/1.webp",
      "/pattern-pictures/dandelion/2.jpg",
      "/pattern-pictures/dandelion/3.jpg",
      "/pattern-pictures/dandelion/4.jpg",
      "/pattern-pictures/dandelion/5.jpg",
      "/pattern-pictures/dandelion/6.jpg",
      "/pattern-pictures/dandelion/7.jpg",
      "/pattern-pictures/dandelion/8.jpg",
      "/pattern-pictures/dandelion/9.jpg",
      "/pattern-pictures/dandelion/10.jpg",
    ],
  },
  {
    productID: 1,
    productName: "Mushroom Stickers",
    productDescription: "This is a mushroom sticker.",
    productPrice: 2.99,
    productCategory: productCategories.Sticker,
    discountRate: 0,
    productThumbnailPath: "/sticker-pictures/mushroom/1.jpg",
    productImages: [
      "/sticker-pictures/mushroom/1.jpg",
      "/sticker-pictures/mushroom/2.jpg",
      "/sticker-pictures/mushroom/3.jpg",
      "/sticker-pictures/mushroom/4.jpg",
      "/sticker-pictures/mushroom/5.jpg",
      "/sticker-pictures/mushroom/6.jpg",
      "/sticker-pictures/mushroom/7.jpg",
    ],
  },
  {
    productID: 2,
    productName: "Hamster Stickers",
    productDescription: "",
    productPrice: 2.99,
    productCategory: productCategories.Sticker,
    discountRate: 0,
    productThumbnailPath: "/sticker-pictures/hamster/1.jpg",
    productImages: [
      "/sticker-pictures/hamster/1.jpg",
      "/sticker-pictures/hamster/2.jpg",
      "/sticker-pictures/hamster/3.jpg",
      "/sticker-pictures/hamster/4.jpg",
      "/sticker-pictures/hamster/5.jpg",
      "/sticker-pictures/hamster/6.jpg",
      "/sticker-pictures/hamster/7.jpg",
      "/sticker-pictures/hamster/8.jpg",
    ],
  },
  {
    productID: 3,
    productName: "Mermaid Stickers",
    productDescription: "",
    productPrice: 2.99,
    productCategory: productCategories.Sticker,
    discountRate: 0,
    productThumbnailPath: "/sticker-pictures/mermaid/1.jpg",
    productImages: [
      "/sticker-pictures/mermaid/1.jpg",
      "/sticker-pictures/mermaid/2.jpg",
      "/sticker-pictures/mermaid/3.jpg",
      "/sticker-pictures/mermaid/4.jpg",
      "/sticker-pictures/mermaid/5.jpg",
      "/sticker-pictures/mermaid/6.jpg",
      "/sticker-pictures/mermaid/7.jpg",
      "/sticker-pictures/mermaid/8.jpg",
      "/sticker-pictures/mermaid/9.jpg",
      "/sticker-pictures/mermaid/10.jpg",
    ],
  },
  {
    productID: 4,
    productName: "Bubble Tea Stickers",
    productDescription: "",
    productPrice: 2.99,
    productCategory: productCategories.Sticker,
    discountRate: 0.15,
    productThumbnailPath: "/sticker-pictures/bubble-tea/1.jpg",
    productImages: [
      "/sticker-pictures/bubble-tea/1.jpg",
      "/sticker-pictures/bubble-tea/2.jpg",
      "/sticker-pictures/bubble-tea/3.jpg",
      "/sticker-pictures/bubble-tea/4.jpg",
      "/sticker-pictures/bubble-tea/5.jpg",
      "/sticker-pictures/bubble-tea/6.jpg",
      "/sticker-pictures/bubble-tea/7.jpg",
      "/sticker-pictures/bubble-tea/8.jpg",
      "/sticker-pictures/bubble-tea/9.jpg",
    ],
  },
  {
    productID: 5,
    productName: "Watercolor Lily Flower Pattern",
    productDescription: "",
    productPrice: 4.99,
    productCategory: productCategories.Sticker,
    discountRate: 0.15,
    productThumbnailPath: "/pattern-pictures/watercolor-lily-flower/1.webp",
    productImages: [
      "/pattern-pictures/watercolor-lily-flower/1.webp",
      "/pattern-pictures/watercolor-lily-flower/2.webp",
      "/pattern-pictures/watercolor-lily-flower/3.webp",
      "/pattern-pictures/watercolor-lily-flower/4.webp",
      "/pattern-pictures/watercolor-lily-flower/5.webp",
      "/pattern-pictures/watercolor-lily-flower/6.webp",
      "/pattern-pictures/watercolor-lily-flower/7.webp",
      "/pattern-pictures/watercolor-lily-flower/8.webp",
      "/pattern-pictures/watercolor-lily-flower/9.webp",
      "/pattern-pictures/watercolor-lily-flower/10.webp",
    ],
  },
  {
    productID: 6,
    productName: "Jewel Pattern",
    productDescription: "",
    productPrice: 3.99,
    productCategory: productCategories.Sticker,
    discountRate: 0.15,
    productThumbnailPath: "/pattern-pictures/jewel/1.webp",
    productImages: [
      "/pattern-pictures/jewel/1.webp",
      "/pattern-pictures/jewel/2.webp",
      "/pattern-pictures/jewel/3.webp",
      "/pattern-pictures/jewel/4.webp",
      "/pattern-pictures/jewel/5.webp",
      "/pattern-pictures/jewel/6.webp",
      "/pattern-pictures/jewel/7.webp",
      "/pattern-pictures/jewel/8.webp",
      "/pattern-pictures/jewel/9.webp",
      "/pattern-pictures/jewel/10.webp",
    ],
  },
  {
    productID: 7,
    productName: "Gold Pattern",
    productDescription: "",
    productPrice: 2.99,
    productCategory: productCategories.Sticker,
    discountRate: 0,
    productThumbnailPath: "/pattern-pictures/gold/1.webp",
    productImages: [
      "/pattern-pictures/gold/1.webp",
      "/pattern-pictures/gold/2.webp",
      "/pattern-pictures/gold/3.webp",
      "/pattern-pictures/gold/4.webp",
      "/pattern-pictures/gold/5.webp",
      "/pattern-pictures/gold/6.webp",
      "/pattern-pictures/gold/7.webp",
      "/pattern-pictures/gold/8.webp",
      "/pattern-pictures/gold/9.webp",
      "/pattern-pictures/gold/10.webp",
    ],
  },
];

function getProduct(id) {
  const filteredProduct = products.find((p) => p.productID == id);
  return filteredProduct;
}

export { products, getProduct };
