import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "../../components/server/Navbar";
import Footer from "../../components/server/Footer";
import PagePadding from "../../components/server/PagePadding";
import PageSizer from "../../components/server/PageSizer";
import CartContext from "../../contexts/CartContext";
import MobileMenu from "../../components/client/MobileMenu";
import MobileMenuToggleContext from "../../contexts/MobileMenuToggleContext";
import CartAddedNotification from "../../components/client/CartAddedNotification";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sticker Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MobileMenuToggleContext>
          <PageSizer>
            <CartContext>
              <Navbar></Navbar>
              <PagePadding>
                {children}
                <Footer></Footer>
                <CartAddedNotification></CartAddedNotification>
              </PagePadding>
            </CartContext>
          </PageSizer>
          <MobileMenu></MobileMenu>
        </MobileMenuToggleContext>
      </body>
    </html>
  );
}
